services:
  dbservice:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3309:3306"  # Expose MySQL port for external access (optional)
    networks:
      - newapp
  myservice:
    build: ./Miko2
    depends_on:
      - dbservice
    environment:
      - spring.datasource.url=jdbc:mysql://dbservice:3306/assemblylang?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=amar
    ports:
      - "8082:9292"

    networks:
      - newapp

networks:
    newapp: