version: '3'
services:
  dbservice:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3307:3306"  # Expose MySQL port for external access (optional)
    networks:
      - assemblyLang

  myservice:
    build: ./assemblyLang
    depends_on:
      - dbservice
    environment:
      - spring.datasource.url=jdbc:mysql://dbservice:3306/assemblylang?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=root
    ports:
      - "8081:9292"

    networks:
      - assemblyLang

networks:
  assemblyLang: